# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

sudo: required
dist: trusty

before_install: make -f travis/Makefile prepare_environment

os:
  - linux

language: cpp
compiler:
  - gcc
  - clang

script: make -f travis/Makefile run-tests
